### ISSUE TITLE
past.Misorien2FZ1 performance

### ISSUE THREAD

**Issue by HeLiuCMU** [HeLiuCMU/HEXOMAP#21]
past.Misorien2FZ1 is about 500 times slower than RotRep.Misorien2FZ1, possible performance fix? @KedoKudo

**Comment by KedoKudo** [comment]
@HeLiuCMU `RotRep.Misorien2FZ1` only considers equivalent orientations (based on crystal symmetry) for one of the two crystal orientations whereas `past.Misorien2FZ1` considers equivalent orientations for both.  I am not sure whether the original implementation, `RotRep.Misorien2FZ1`, can capture all cases.  I think some derivation is necessary to ensure that we are not missing any cases.

**Comment by Yufeng-shen** [comment]
If I remember correctly, Misorien2FZ1 only tries to get the 1D angle instead of the whole 3D angle of misorientation. It is useful in some cases. I’m not 100% sure, you can double check that.

**Comment by KedoKudo** [comment]
It seems like all other libraries only use one symmetry operator when calculating the misorientation when two orientations are of the same lattice.  I will make the change to `past.Misorien2FZ1` after some additional testing.

**Comment by KedoKudo** [comment]
The pull request, #22, should address most of the issue discussed here.  I think we can safely close the issue once #22 is merged.

**Comment by HeLiuCMU** [comment]
pull request #22
