### ISSUE TITLE
Quaternion.as_euler

### ISSUE THREAD

**Issue by HeLiuCMU** [HeLiuCMU/HEXOMAP#23]
@KedoKudo 
I have tried to use Quaternion.as_euler but notice unexpected result. after transfer initial euler to quaternion and then transfer back to euler, the euler angle is different from the initial one. I checked the misorientation and they are indeed different angles. Can you help check it is because I do something wrong or it is a potential bug in the code? Thanks.
Below is the test code:
eulers = np.array([ 40.42179605,  38.31625586, 349.25393643])/180.0*np.pi
quats = Quaternion.quaternions_from_eulers(eulers).ravel()
quat = Quaternion(quats[0],quats[1],quats[2],quats[3])
#quat = Quaternion.from_eulers(Eulers(eulers[0],eulers[1],eulers[2]))
eulersNew = quat.as_eulers.as_array
print(f'quats: {quats}\nnew euluer: {eulersNew/np.pi*180.0}')

The result:
quats: [0.91311761 0.29599992 0.14171733 0.24190179]
new euluer: [190.74606357  38.31625586 139.57820395]

**Comment by KedoKudo** [comment]
It seems to me the quat.as_eulers is not compatible with the reformulated quaternion.from_eulers.  On a related note, the orientation paper from 2015 was indeed using a completely different convention.  I will look into this and work on a fix right away.

**Comment by HeLiuCMU** [comment]
I managed to find a correct method to transform quaternion to euler, it is adapted from https://stackoverflow.com/questions/11103683/euler-angle-to-quaternion-then-quaternion-to-euler-angle, I hope this will help. I don't know how to keep format here. I can send you a copy if you need.
`
class Q():
    def __init__(self, quat):
        self.w = quat[0]
        self.x = quat[1]
        self.y = quat[2]
        self.z = quat[3]
def twoaxisrot(r11, r12, r21, r31, r32):
    print('two axis rot')
    res = np.empty(3)
    res[0] = np.arctan2( r11, r12 )
    res[1] = np.arccos ( r21 )
    res[2] = np.arctan2( r31, r32 )
    return res

def threeaxisrot(r11, r12, r21, r31, r32):
    res = np.empty(3)
    res[0] = np.arctan2( r31, r32 )
    res[1] = np.arcsin ( r21 )
    res[2] = np.arctan2( r11, r12 )
    return res
def quaternion2Euler(q,rotSeq='zxz'):
    if rotSeq=='zxz':
        res = twoaxisrot( 2*(q.x*q.z + q.w*q.y),
                  -2*(q.y*q.z - q.w*q.x),
                   q.w*q.w - q.x*q.x - q.y*q.y + q.z*q.z,
                   2*(q.x*q.z - q.w*q.y),
                   2*(q.y*q.z + q.w*q.x))
    else:
        print("Unknown rotation sequence")
        return
    for i in range(res.size):
        while res[i]<0:
            res[i] += 2*np.pi
        while res[i]>2*np.pi:
            res[i] -= 2*np.pi
    return res
eulers = np.array([ 40.42179605,  38.31625586, 349.25393643])/180.0*np.pi
quats = Quaternion.quaternions_from_eulers(eulers).ravel()
print(quats)
q = Q(quats)
res = quaternion2Euler(q)
print(res/np.pi*180)
`

**Comment by KedoKudo** [comment]
Thanks, @HeLiuCMU.  A copy would be really helpful.  Also,  I think it's better if I do the derivation at least once to make sure that we have a record for future development.
